test: Add more unit tests [DEV-2506]
cheqd/did-resolver pull request #140
Opened 2023-04-23 17:06 UTC by anikitinDSR

2023-04-23 17:06 UTC, ankurdotb commented
Task linked: [DEV-2506 Create unit tests for DID URL dereferencing](https://app.clickup.com/t/6600954/DEV-2506)

2023-04-25 07:22 UTC, abdulla-ashurov requested changes
A great job! 🔥

2023-04-25 07:22 UTC, abdulla-ashurov commented on tests/unit/diddoc/request/diddoc_service_params_test.go
> +	// Negative Cases
Let's add a negative test for testing `relativeRef` query without `service` query.

2023-04-25 07:22 UTC, abdulla-ashurov commented on tests/unit/test_utils.go
> +	var metadata_list = make([]*resourceTypes.Metadata, len(ls.Resources))
Rename this local variable from `metadata_list` to `metadataList` to match golang code style.

2023-04-25 08:38 UTC, abdulla-ashurov approved these changes

2023-04-25 09:16 UTC, merged